# Generated by Django 5.1.7 on 2025-04-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
