# Generated by Django 5.1.7 on 2025-04-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available!'), ('checked_out', 'Checked Out')], default='available', max_length=12),
        ),
    ]
